//
// SystemInformationAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class SystemInformationAPI: APIBase {
    /**
     Gets SEMP API version and platform information.
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getSystemInformation(completion: ((data: SystemInformationResponse?, error: ErrorType?) -> Void)) {
        getSystemInformationWithRequestBuilder().execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Gets SEMP API version and platform information.
     - GET /systemInformation
     - Gets SEMP API version and platform information.  A SEMP client authorized with a minimum access scope/level of \"global/none\" is required to perform this operation.  This has been available since 2.1.0.  This has been deprecated since 2.2.0.
     - BASIC:
       - type: basic
       - name: basicAuth
     - examples: [{contentType=application/json, example={
  "data" : {
    "sempVersion" : "sempVersion",
    "platform" : "platform"
  },
  "meta" : {
    "request" : {
      "method" : "method",
      "uri" : "uri"
    },
    "paging" : {
      "nextPageUri" : "nextPageUri",
      "cursorQuery" : "cursorQuery"
    },
    "error" : {
      "code" : 0,
      "description" : "description",
      "status" : "status"
    },
    "responseCode" : 6
  },
  "links" : {
    "uri" : "uri"
  }
}}]

     - returns: RequestBuilder<SystemInformationResponse> 
     */
    public class func getSystemInformationWithRequestBuilder() -> RequestBuilder<SystemInformationResponse> {
        let path = "/systemInformation"
        let URLString = solace_semp_clientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<SystemInformationResponse>.Type = solace_semp_clientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

}
