//
// AboutUser.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class AboutUser: JSONEncodable {
    public enum GlobalAccessLevel: String { 
        case Admin = "admin"
        case None = "none"
        case ReadOnly = "read-only"
        case ReadWrite = "read-write"
    }
    /** Global access level of the Current User. The allowed values and their meaning are:  &lt;pre&gt; \&quot;admin\&quot; - Administrative access allowed. \&quot;none\&quot; - No access allowed. \&quot;read-only\&quot; - Read only. \&quot;read-write\&quot; - Read and Write. &lt;/pre&gt;  */
    public var globalAccessLevel: GlobalAccessLevel?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["globalAccessLevel"] = self.globalAccessLevel?.rawValue
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
