//
// AboutUserLinks.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class AboutUserLinks: JSONEncodable {
    /** The URI of this AboutUser&#39;s msgVpns collection. */
    public var msgVpnsUri: String?
    /** The URI of this AboutUser object. */
    public var uri: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["msgVpnsUri"] = self.msgVpnsUri
        nillableDictionary["uri"] = self.uri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
