//
// AboutUserMsgVpn.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class AboutUserMsgVpn: JSONEncodable {
    public enum AccessLevel: String { 
        case None = "none"
        case ReadOnly = "read-only"
        case ReadWrite = "read-write"
    }
    /** Message VPN access level of the Current User. The allowed values and their meaning are:  &lt;pre&gt; \&quot;none\&quot; - No access allowed. \&quot;read-only\&quot; - Read only. \&quot;read-write\&quot; - Read and Write. &lt;/pre&gt;  */
    public var accessLevel: AccessLevel?
    /** The name of the Message VPN. */
    public var msgVpnName: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["accessLevel"] = self.accessLevel?.rawValue
        nillableDictionary["msgVpnName"] = self.msgVpnName
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
