//
// EventThresholdByValue.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class EventThresholdByValue: JSONEncodable {
    /** Threshold clear value. */
    public var clearValue: Int64?
    /** Threshold set value. */
    public var setValue: Int64?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["clearValue"] = self.clearValue?.encodeToJSON()
        nillableDictionary["setValue"] = self.setValue?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
