//
// EventThresholdByPercent.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class EventThresholdByPercent: JSONEncodable {
    /** The clear threshold for the value of this counter as percentage of its maximum value. Falling below this value will trigger a corresponding Event. */
    public var clearPercent: Int64?
    /** The set threshold for the value of this counter as percentage of its maximum value. Exceeding this value will trigger a corresponding Event. */
    public var setPercent: Int64?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["clearPercent"] = self.clearPercent?.encodeToJSON()
        nillableDictionary["setPercent"] = self.setPercent?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
