//
// MsgVpnJndiTopic.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class MsgVpnJndiTopic: JSONEncodable {
    /** The name of the Message VPN. */
    public var msgVpnName: String?
    /** The physical name of the JMS Topic. The default value is &#x60;\&quot;\&quot;&#x60;. */
    public var physicalName: String?
    /** The JNDI name of the JMS Topic. */
    public var topicName: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["msgVpnName"] = self.msgVpnName
        nillableDictionary["physicalName"] = self.physicalName
        nillableDictionary["topicName"] = self.topicName
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
