//
// MsgVpnBridgeRemoteMsgVpn.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class MsgVpnBridgeRemoteMsgVpn: JSONEncodable {
    public enum BridgeVirtualRouter: String { 
        case Primary = "primary"
        case Backup = "backup"
        case Auto = "auto"
    }
    /** The name of the Bridge. */
    public var bridgeName: String?
    /** Specify whether the Bridge is configured for the primary or backup Virtual Router or auto configured. The allowed values and their meaning are:  &lt;pre&gt; \&quot;primary\&quot; - The Bridge is used for the primary Virtual Router. \&quot;backup\&quot; - The Bridge is used for the backup Virtual Router. \&quot;auto\&quot; - The Bridge is automatically assigned a Router. &lt;/pre&gt;  */
    public var bridgeVirtualRouter: BridgeVirtualRouter?
    /** The Client Username the Bridge uses to login to the Remote Message VPN. This per Remote Message VPN value overrides the value provided for the bridge overall. The default value is &#x60;\&quot;\&quot;&#x60;. */
    public var clientUsername: String?
    /** Enable or disable data compression for the Remote Message VPN. The default value is &#x60;false&#x60;. */
    public var compressedDataEnabled: Bool?
    /** The order in which attempts to connect to different Message VPN hosts are attempted, or the preference given to incoming connections from remote routers, from 1 (highest priority) to 4 (lowest priority). The default value is &#x60;4&#x60;. */
    public var connectOrder: Int32?
    /** Indicates how many outstanding guaranteed messages can be sent over the Remote Message VPN connection before acknowledgement is received by the sender. The default value is &#x60;255&#x60;. */
    public var egressFlowWindowSize: Int64?
    /** Enable or disable the Remote Message VPN. The default value is &#x60;false&#x60;. */
    public var enabled: Bool?
    /** The name of the Message VPN. */
    public var msgVpnName: String?
    /** The password for the Client Username that the Bridge uses to login to the Remote Message VPN. The default is to have no &#x60;password&#x60;. */
    public var password: String?
    /** The queue binding of the Bridge for the Remote Message VPN. The Bridge attempts to bind to that queue over the Bridge link once the link has been established, or immediately if it already is established. The queue must be configured on the remote router when the Bridge connection is established. If the bind fails an event log is generated which includes the reason for the failure. The default value is &#x60;\&quot;\&quot;&#x60;. */
    public var queueBinding: String?
    /** The interface on the local router through which to access the Remote Message VPN. If not provided (recommended) then an interface will be chosen automatically based on routing tables. If an interface is provided, \&quot;remoteMsgVpnLocation\&quot; must be either a hostname or IP Address, not a virtual router-name. */
    public var remoteMsgVpnInterface: String?
    /** The location of the Remote Message VPN. This may be given as either an FQDN (resolvable via DNS), IP Address, or virtual router-name (starts with &#39;v:&#39;). If specified as a FQDN or IP Address, a port must be specified as well. */
    public var remoteMsgVpnLocation: String?
    /** The name of the Remote Message VPN. */
    public var remoteMsgVpnName: String?
    /** Enable or disable TLS for the Remote Message VPN. The default value is &#x60;false&#x60;. */
    public var tlsEnabled: Bool?
    /** The Client Profile for the unidirectional Bridge for the Remote Message VPN. The Client Profile must exist in the local Message VPN, and it is used only for the TCP parameters. The default value is &#x60;\&quot;#client-profile\&quot;&#x60;. */
    public var unidirectionalClientProfile: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["bridgeName"] = self.bridgeName
        nillableDictionary["bridgeVirtualRouter"] = self.bridgeVirtualRouter?.rawValue
        nillableDictionary["clientUsername"] = self.clientUsername
        nillableDictionary["compressedDataEnabled"] = self.compressedDataEnabled
        nillableDictionary["connectOrder"] = self.connectOrder?.encodeToJSON()
        nillableDictionary["egressFlowWindowSize"] = self.egressFlowWindowSize?.encodeToJSON()
        nillableDictionary["enabled"] = self.enabled
        nillableDictionary["msgVpnName"] = self.msgVpnName
        nillableDictionary["password"] = self.password
        nillableDictionary["queueBinding"] = self.queueBinding
        nillableDictionary["remoteMsgVpnInterface"] = self.remoteMsgVpnInterface
        nillableDictionary["remoteMsgVpnLocation"] = self.remoteMsgVpnLocation
        nillableDictionary["remoteMsgVpnName"] = self.remoteMsgVpnName
        nillableDictionary["tlsEnabled"] = self.tlsEnabled
        nillableDictionary["unidirectionalClientProfile"] = self.unidirectionalClientProfile
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
