//
// MsgVpnRestDeliveryPoint.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class MsgVpnRestDeliveryPoint: JSONEncodable {
    /** The Client Profile of the REST Delivery Point. It must exist in the local Message VPN. Its TCP parameters are used for all REST Consumers in this RDP. Its queue properties are used by the RDP client. The Client Profile is used inside the auto-generated Client Username for this RDP. The default value is &#x60;\&quot;default\&quot;&#x60;. */
    public var clientProfileName: String?
    /** Enable or disable the REST Delivery Point. When disabled, no connections are initiated or messages delivered to any of the contained REST Consumers. The default value is &#x60;false&#x60;. */
    public var enabled: Bool?
    /** The name of the Message VPN. */
    public var msgVpnName: String?
    /** The name of the REST Delivery Point. */
    public var restDeliveryPointName: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["clientProfileName"] = self.clientProfileName
        nillableDictionary["enabled"] = self.enabled
        nillableDictionary["msgVpnName"] = self.msgVpnName
        nillableDictionary["restDeliveryPointName"] = self.restDeliveryPointName
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
