//
// MsgVpnAclProfileLinks.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class MsgVpnAclProfileLinks: JSONEncodable {
    /** The URI of this MsgVpnAclProfile&#39;s clientConnectExceptions collection. */
    public var clientConnectExceptionsUri: String?
    /** The URI of this MsgVpnAclProfile&#39;s publishExceptions collection. */
    public var publishExceptionsUri: String?
    /** The URI of this MsgVpnAclProfile&#39;s subscribeExceptions collection. */
    public var subscribeExceptionsUri: String?
    /** The URI of this MsgVpnAclProfile object. */
    public var uri: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["clientConnectExceptionsUri"] = self.clientConnectExceptionsUri
        nillableDictionary["publishExceptionsUri"] = self.publishExceptionsUri
        nillableDictionary["subscribeExceptionsUri"] = self.subscribeExceptionsUri
        nillableDictionary["uri"] = self.uri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
