//
// MsgVpnQueueSubscription.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class MsgVpnQueueSubscription: JSONEncodable {
    /** The name of the Message VPN. */
    public var msgVpnName: String?
    /** The name of the Queue. */
    public var queueName: String?
    /** The Topic of the Subscription. */
    public var subscriptionTopic: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["msgVpnName"] = self.msgVpnName
        nillableDictionary["queueName"] = self.queueName
        nillableDictionary["subscriptionTopic"] = self.subscriptionTopic
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
