//
// MsgVpnSequencedTopic.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class MsgVpnSequencedTopic: JSONEncodable {
    /** The name of the Message VPN. */
    public var msgVpnName: String?
    /** Topic for applying sequence numbers. */
    public var sequencedTopic: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["msgVpnName"] = self.msgVpnName
        nillableDictionary["sequencedTopic"] = self.sequencedTopic
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
