//
// MsgVpnRestDeliveryPointRestConsumerTlsTrustedCommonName.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class MsgVpnRestDeliveryPointRestConsumerTlsTrustedCommonName: JSONEncodable {
    /** The name of the Message VPN. */
    public var msgVpnName: String?
    /** The name of the REST Consumer. */
    public var restConsumerName: String?
    /** The name of the REST Delivery Point. */
    public var restDeliveryPointName: String?
    /** The expected trusted common name of the remote certificate. */
    public var tlsTrustedCommonName: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["msgVpnName"] = self.msgVpnName
        nillableDictionary["restConsumerName"] = self.restConsumerName
        nillableDictionary["restDeliveryPointName"] = self.restDeliveryPointName
        nillableDictionary["tlsTrustedCommonName"] = self.tlsTrustedCommonName
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
