//
// MsgVpnReplayLog.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class MsgVpnReplayLog: JSONEncodable {
    /** Enable or disable the egress flow of messages from the Replay Log. The default value is &#x60;false&#x60;. */
    public var egressEnabled: Bool?
    /** Enable or disable the ingress flow of messages to the Replay Log. The default value is &#x60;false&#x60;. */
    public var ingressEnabled: Bool?
    /** The maximum spool usage in megabytes (MB) allowed by the Replay Log. If this limit is exceeded, old messages will be trimmed. The default value is &#x60;0&#x60;. */
    public var maxSpoolUsage: Int64?
    /** The name of the Message VPN. */
    public var msgVpnName: String?
    /** The name of the Replay Log. */
    public var replayLogName: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["egressEnabled"] = self.egressEnabled
        nillableDictionary["ingressEnabled"] = self.ingressEnabled
        nillableDictionary["maxSpoolUsage"] = self.maxSpoolUsage?.encodeToJSON()
        nillableDictionary["msgVpnName"] = self.msgVpnName
        nillableDictionary["replayLogName"] = self.replayLogName
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
