//
// MsgVpnAclProfile.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class MsgVpnAclProfile: JSONEncodable {
    public enum ClientConnectDefaultAction: String { 
        case Allow = "allow"
        case Disallow = "disallow"
    }
    public enum PublishTopicDefaultAction: String { 
        case Allow = "allow"
        case Disallow = "disallow"
    }
    public enum SubscribeTopicDefaultAction: String { 
        case Allow = "allow"
        case Disallow = "disallow"
    }
    /** The name of the ACL Profile. */
    public var aclProfileName: String?
    /** The default action when a Client connects to the Message VPN. The default value is &#x60;\&quot;disallow\&quot;&#x60;. The allowed values and their meaning are:  &lt;pre&gt; \&quot;allow\&quot; - Allow client connection unless an exception is found for it. \&quot;disallow\&quot; - Disallow client connection unless an exception is found for it. &lt;/pre&gt;  */
    public var clientConnectDefaultAction: ClientConnectDefaultAction?
    /** The name of the Message VPN. */
    public var msgVpnName: String?
    /** The default action to take when a Client publishes to a Topic in the Message VPN. The default value is &#x60;\&quot;disallow\&quot;&#x60;. The allowed values and their meaning are:  &lt;pre&gt; \&quot;allow\&quot; - Allow topic unless an exception is found for it. \&quot;disallow\&quot; - Disallow topic unless an exception is found for it. &lt;/pre&gt;  */
    public var publishTopicDefaultAction: PublishTopicDefaultAction?
    /** The default action to take when a Client subscribes to a Topic. The default value is &#x60;\&quot;disallow\&quot;&#x60;. The allowed values and their meaning are:  &lt;pre&gt; \&quot;allow\&quot; - Allow topic unless an exception is found for it. \&quot;disallow\&quot; - Disallow topic unless an exception is found for it. &lt;/pre&gt;  */
    public var subscribeTopicDefaultAction: SubscribeTopicDefaultAction?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["aclProfileName"] = self.aclProfileName
        nillableDictionary["clientConnectDefaultAction"] = self.clientConnectDefaultAction?.rawValue
        nillableDictionary["msgVpnName"] = self.msgVpnName
        nillableDictionary["publishTopicDefaultAction"] = self.publishTopicDefaultAction?.rawValue
        nillableDictionary["subscribeTopicDefaultAction"] = self.subscribeTopicDefaultAction?.rawValue
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
