//
// MsgVpnClientProfile.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class MsgVpnClientProfile: JSONEncodable {
    /** Allow or deny Bridge clients to connect. Changing this setting does not affect existing Bridge client connections. The default value is &#x60;false&#x60;. */
    public var allowBridgeConnectionsEnabled: Bool?
    /** Allow or deny clients to bind to topic endpoints or queues with the cut-through delivery mode. Changing this setting does not affect existing client connections. The default value is &#x60;false&#x60;. */
    public var allowCutThroughForwardingEnabled: Bool?
    /** Allow or deny clients to create topic endponts or queues. Changing this setting does not affect existing client connections. The default value is &#x60;false&#x60;. */
    public var allowGuaranteedEndpointCreateEnabled: Bool?
    /** Allow or deny clients to receive guaranteed messages. Changing this setting does not affect existing client connections. The default value is &#x60;false&#x60;. */
    public var allowGuaranteedMsgReceiveEnabled: Bool?
    /** Allow or deny clients to send guaranteed messages. Changing this setting does not affect existing client connections. The default value is &#x60;false&#x60;. */
    public var allowGuaranteedMsgSendEnabled: Bool?
    /** Allow or deny clients to establish transacted sessions. Changing this setting does not affect existing client connections. The default value is &#x60;false&#x60;. */
    public var allowTransactedSessionsEnabled: Bool?
    /** The name of a Queue to copy settings from when a new Queue is created by an API. The referenced Queue must exist on the Message VPN. The default value is &#x60;\&quot;\&quot;&#x60;. */
    public var apiQueueManagementCopyFromOnCreateName: String?
    /** The name of a Topic Endpoint to copy settings from when a new Topic Endpoint is created by an API. The referenced Topic Endpoint must exist on the Message VPN. The default value is &#x60;\&quot;\&quot;&#x60;. */
    public var apiTopicEndpointManagementCopyFromOnCreateName: String?
    /** The Client Profile name. */
    public var clientProfileName: String?
    /** Enable or disable whether connected clients are allowed to use compression. The default value is &#x60;true&#x60;. Available since 2.10. */
    public var compressionEnabled: Bool?
    /** The amount of time to delay the delivery of messages to clients after the initial message has been delivered (the eliding delay interval), in milliseconds. Zero value means there is no delay in delivering messages to clients. The default value is &#x60;0&#x60;. */
    public var elidingDelay: Int64?
    /** Enable or disable the Message Eliding. The default value is &#x60;false&#x60;. */
    public var elidingEnabled: Bool?
    /** The maximum number of topics tracked for Message Eliding per one Client connection. The default value is &#x60;256&#x60;. */
    public var elidingMaxTopicCount: Int64?
    public var eventClientProvisionedEndpointSpoolUsageThreshold: EventThresholdByPercent?
    public var eventConnectionCountPerClientUsernameThreshold: EventThreshold?
    public var eventEgressFlowCountThreshold: EventThreshold?
    public var eventEndpointCountPerClientUsernameThreshold: EventThreshold?
    public var eventIngressFlowCountThreshold: EventThreshold?
    public var eventServiceSmfConnectionCountPerClientUsernameThreshold: EventThreshold?
    public var eventServiceWebConnectionCountPerClientUsernameThreshold: EventThreshold?
    public var eventSubscriptionCountThreshold: EventThreshold?
    public var eventTransactedSessionCountThreshold: EventThreshold?
    public var eventTransactionCountThreshold: EventThreshold?
    /** The maximum number of client connections that can be simultaneously connected with the same Client Username. The default is the max value supported by the hardware. */
    public var maxConnectionCountPerClientUsername: Int64?
    /** The maximum number of egress flows that can be created by one client. The default is the max value supported by the hardware. */
    public var maxEgressFlowCount: Int64?
    /** The maximum number of queues and topic endpoints that can be created by clients with the same Client Username. The default is the max value supported by the hardware. */
    public var maxEndpointCountPerClientUsername: Int64?
    /** The maximum number of ingress flows that can be created by one client. The default is the max value supported by the hardware. */
    public var maxIngressFlowCount: Int64?
    /** The maximum number of subscriptions that can be created by one client. The default varies by platform. */
    public var maxSubscriptionCount: Int64?
    /** The maximum number of transacted sessions that can be created by one client. The default value is &#x60;10&#x60;. */
    public var maxTransactedSessionCount: Int64?
    /** The maximum number of transactions that can be created by one client. The default varies by platform. */
    public var maxTransactionCount: Int64?
    /** The name of the Message VPN. */
    public var msgVpnName: String?
    /** The maximum depth of the \&quot;Control 1\&quot; (C-1) priority queue, in work units. Each work unit is 2048 bytes of message data. The default value is &#x60;20000&#x60;. */
    public var queueControl1MaxDepth: Int32?
    /** The number of messages that are always allowed entry into the \&quot;Control 1\&quot; (C-1) priority queue, regardless of the \&quot;queueControl1MaxDepth\&quot; value. The default value is &#x60;4&#x60;. */
    public var queueControl1MinMsgBurst: Int32?
    /** The maximum depth of the \&quot;Direct 1\&quot; (D-1) priority queue, in work units. Each work unit is 2048 bytes of message data. The default value is &#x60;20000&#x60;. */
    public var queueDirect1MaxDepth: Int32?
    /** The number of messages that are always allowed entry into the \&quot;Direct 1\&quot; (D-1) priority queue, regardless of the \&quot;queueDirect1MaxDepth\&quot; value. The default value is &#x60;4&#x60;. */
    public var queueDirect1MinMsgBurst: Int32?
    /** The maximum depth of the \&quot;Direct 2\&quot; (D-2) priority queue, in work units. Each work unit is 2048 bytes of message data. The default value is &#x60;20000&#x60;. */
    public var queueDirect2MaxDepth: Int32?
    /** The number of messages that are always allowed entry into the \&quot;Direct 2\&quot; (D-2) priority queue, regardless of the \&quot;queueDirect2MaxDepth\&quot; value. The default value is &#x60;4&#x60;. */
    public var queueDirect2MinMsgBurst: Int32?
    /** The maximum depth of the \&quot;Direct 3\&quot; (D-3) priority queue, in work units. Each work unit is 2048 bytes of message data. The default value is &#x60;20000&#x60;. */
    public var queueDirect3MaxDepth: Int32?
    /** The number of messages that are always allowed entry into the \&quot;Direct 3\&quot; (D-3) priority queue, regardless of the \&quot;queueDirect3MaxDepth\&quot; value. The default value is &#x60;4&#x60;. */
    public var queueDirect3MinMsgBurst: Int32?
    /** The maximum depth of the \&quot;Guaranteed 1\&quot; (G-1) priority queue, in work units. Each work unit is 2048 bytes of message data. The default value is &#x60;20000&#x60;. */
    public var queueGuaranteed1MaxDepth: Int32?
    /** The number of messages that are always allowed entry into the \&quot;Guaranteed 1\&quot; (G-3) priority queue, regardless of the \&quot;queueGuaranteed1MaxDepth\&quot; value. The default value is &#x60;255&#x60;. */
    public var queueGuaranteed1MinMsgBurst: Int32?
    /** Enable or disable sending of a negative acknowledgement (NACK) on the discard of a message because of a message subscription was not found. The default value is &#x60;false&#x60;. Available since 2.2. */
    public var rejectMsgToSenderOnNoSubscriptionMatchEnabled: Bool?
    /** Allow or deny clients to connect to the Message VPN if its Replication state is standby. The default value is &#x60;false&#x60;. */
    public var replicationAllowClientConnectWhenStandbyEnabled: Bool?
    /** The maximum number of SMF client connections that can be simultaneously connected with the same Client Username. The default is the max value supported by the hardware. */
    public var serviceSmfMaxConnectionCountPerClientUsername: Int64?
    /** The timeout for inactive Web Transport client sessions, in seconds. The default value is &#x60;30&#x60;. */
    public var serviceWebInactiveTimeout: Int64?
    /** The maximum number of Web Transport client connections that can be simultaneously connected with the same Client Username. The default is the max value supported by the hardware. */
    public var serviceWebMaxConnectionCountPerClientUsername: Int64?
    /** The maximum Web Transport payload size before its fragmentation occurs, in bytes. The size of the header is not included. The default value is &#x60;1000000&#x60;. */
    public var serviceWebMaxPayload: Int64?
    /** The TCP initial congestion window size, in multiple of the TCP Maximum Segment Size (MSS). Changing the value from its default of 2 results in non-compliance with RFC 2581. Contact Solace Support before changing this value. The default value is &#x60;2&#x60;. */
    public var tcpCongestionWindowSize: Int64?
    /** The number of TCP keepalive retransmissions to be carried out before declaring that the remote end is not available. The default value is &#x60;5&#x60;. */
    public var tcpKeepaliveCount: Int64?
    /** The amount of time a connection must remain idle before TCP begins sending keepalive probes, in seconds. The default value is &#x60;3&#x60;. */
    public var tcpKeepaliveIdleTime: Int64?
    /** The amount of time between TCP keepalive retransmissions when no acknowledgement is received, in seconds. The default value is &#x60;1&#x60;. */
    public var tcpKeepaliveInterval: Int64?
    /** The TCP maximum segment size, in kilobytes. Changes are applied to all existing connections. The default value is &#x60;1460&#x60;. */
    public var tcpMaxSegmentSize: Int64?
    /** The TCP maximum window size, in kilobytes. Changes are applied to all existing connections. The default value is &#x60;256&#x60;. */
    public var tcpMaxWindowSize: Int64?
    /** Enable or disable allowing a client to downgrade an encrypted connection to plain text. The default value is &#x60;true&#x60;. Available since 2.8. */
    public var tlsAllowDowngradeToPlainTextEnabled: Bool?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["allowBridgeConnectionsEnabled"] = self.allowBridgeConnectionsEnabled
        nillableDictionary["allowCutThroughForwardingEnabled"] = self.allowCutThroughForwardingEnabled
        nillableDictionary["allowGuaranteedEndpointCreateEnabled"] = self.allowGuaranteedEndpointCreateEnabled
        nillableDictionary["allowGuaranteedMsgReceiveEnabled"] = self.allowGuaranteedMsgReceiveEnabled
        nillableDictionary["allowGuaranteedMsgSendEnabled"] = self.allowGuaranteedMsgSendEnabled
        nillableDictionary["allowTransactedSessionsEnabled"] = self.allowTransactedSessionsEnabled
        nillableDictionary["apiQueueManagementCopyFromOnCreateName"] = self.apiQueueManagementCopyFromOnCreateName
        nillableDictionary["apiTopicEndpointManagementCopyFromOnCreateName"] = self.apiTopicEndpointManagementCopyFromOnCreateName
        nillableDictionary["clientProfileName"] = self.clientProfileName
        nillableDictionary["compressionEnabled"] = self.compressionEnabled
        nillableDictionary["elidingDelay"] = self.elidingDelay?.encodeToJSON()
        nillableDictionary["elidingEnabled"] = self.elidingEnabled
        nillableDictionary["elidingMaxTopicCount"] = self.elidingMaxTopicCount?.encodeToJSON()
        nillableDictionary["eventClientProvisionedEndpointSpoolUsageThreshold"] = self.eventClientProvisionedEndpointSpoolUsageThreshold?.encodeToJSON()
        nillableDictionary["eventConnectionCountPerClientUsernameThreshold"] = self.eventConnectionCountPerClientUsernameThreshold?.encodeToJSON()
        nillableDictionary["eventEgressFlowCountThreshold"] = self.eventEgressFlowCountThreshold?.encodeToJSON()
        nillableDictionary["eventEndpointCountPerClientUsernameThreshold"] = self.eventEndpointCountPerClientUsernameThreshold?.encodeToJSON()
        nillableDictionary["eventIngressFlowCountThreshold"] = self.eventIngressFlowCountThreshold?.encodeToJSON()
        nillableDictionary["eventServiceSmfConnectionCountPerClientUsernameThreshold"] = self.eventServiceSmfConnectionCountPerClientUsernameThreshold?.encodeToJSON()
        nillableDictionary["eventServiceWebConnectionCountPerClientUsernameThreshold"] = self.eventServiceWebConnectionCountPerClientUsernameThreshold?.encodeToJSON()
        nillableDictionary["eventSubscriptionCountThreshold"] = self.eventSubscriptionCountThreshold?.encodeToJSON()
        nillableDictionary["eventTransactedSessionCountThreshold"] = self.eventTransactedSessionCountThreshold?.encodeToJSON()
        nillableDictionary["eventTransactionCountThreshold"] = self.eventTransactionCountThreshold?.encodeToJSON()
        nillableDictionary["maxConnectionCountPerClientUsername"] = self.maxConnectionCountPerClientUsername?.encodeToJSON()
        nillableDictionary["maxEgressFlowCount"] = self.maxEgressFlowCount?.encodeToJSON()
        nillableDictionary["maxEndpointCountPerClientUsername"] = self.maxEndpointCountPerClientUsername?.encodeToJSON()
        nillableDictionary["maxIngressFlowCount"] = self.maxIngressFlowCount?.encodeToJSON()
        nillableDictionary["maxSubscriptionCount"] = self.maxSubscriptionCount?.encodeToJSON()
        nillableDictionary["maxTransactedSessionCount"] = self.maxTransactedSessionCount?.encodeToJSON()
        nillableDictionary["maxTransactionCount"] = self.maxTransactionCount?.encodeToJSON()
        nillableDictionary["msgVpnName"] = self.msgVpnName
        nillableDictionary["queueControl1MaxDepth"] = self.queueControl1MaxDepth?.encodeToJSON()
        nillableDictionary["queueControl1MinMsgBurst"] = self.queueControl1MinMsgBurst?.encodeToJSON()
        nillableDictionary["queueDirect1MaxDepth"] = self.queueDirect1MaxDepth?.encodeToJSON()
        nillableDictionary["queueDirect1MinMsgBurst"] = self.queueDirect1MinMsgBurst?.encodeToJSON()
        nillableDictionary["queueDirect2MaxDepth"] = self.queueDirect2MaxDepth?.encodeToJSON()
        nillableDictionary["queueDirect2MinMsgBurst"] = self.queueDirect2MinMsgBurst?.encodeToJSON()
        nillableDictionary["queueDirect3MaxDepth"] = self.queueDirect3MaxDepth?.encodeToJSON()
        nillableDictionary["queueDirect3MinMsgBurst"] = self.queueDirect3MinMsgBurst?.encodeToJSON()
        nillableDictionary["queueGuaranteed1MaxDepth"] = self.queueGuaranteed1MaxDepth?.encodeToJSON()
        nillableDictionary["queueGuaranteed1MinMsgBurst"] = self.queueGuaranteed1MinMsgBurst?.encodeToJSON()
        nillableDictionary["rejectMsgToSenderOnNoSubscriptionMatchEnabled"] = self.rejectMsgToSenderOnNoSubscriptionMatchEnabled
        nillableDictionary["replicationAllowClientConnectWhenStandbyEnabled"] = self.replicationAllowClientConnectWhenStandbyEnabled
        nillableDictionary["serviceSmfMaxConnectionCountPerClientUsername"] = self.serviceSmfMaxConnectionCountPerClientUsername?.encodeToJSON()
        nillableDictionary["serviceWebInactiveTimeout"] = self.serviceWebInactiveTimeout?.encodeToJSON()
        nillableDictionary["serviceWebMaxConnectionCountPerClientUsername"] = self.serviceWebMaxConnectionCountPerClientUsername?.encodeToJSON()
        nillableDictionary["serviceWebMaxPayload"] = self.serviceWebMaxPayload?.encodeToJSON()
        nillableDictionary["tcpCongestionWindowSize"] = self.tcpCongestionWindowSize?.encodeToJSON()
        nillableDictionary["tcpKeepaliveCount"] = self.tcpKeepaliveCount?.encodeToJSON()
        nillableDictionary["tcpKeepaliveIdleTime"] = self.tcpKeepaliveIdleTime?.encodeToJSON()
        nillableDictionary["tcpKeepaliveInterval"] = self.tcpKeepaliveInterval?.encodeToJSON()
        nillableDictionary["tcpMaxSegmentSize"] = self.tcpMaxSegmentSize?.encodeToJSON()
        nillableDictionary["tcpMaxWindowSize"] = self.tcpMaxWindowSize?.encodeToJSON()
        nillableDictionary["tlsAllowDowngradeToPlainTextEnabled"] = self.tlsAllowDowngradeToPlainTextEnabled
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
