//
// MsgVpnLinks.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class MsgVpnLinks: JSONEncodable {
    /** The URI of this MsgVpn&#39;s aclProfiles collection. */
    public var aclProfilesUri: String?
    /** The URI of this MsgVpn&#39;s authorizationGroups collection. */
    public var authorizationGroupsUri: String?
    /** The URI of this MsgVpn&#39;s bridges collection. */
    public var bridgesUri: String?
    /** The URI of this MsgVpn&#39;s clientProfiles collection. */
    public var clientProfilesUri: String?
    /** The URI of this MsgVpn&#39;s clientUsernames collection. */
    public var clientUsernamesUri: String?
    /** The URI of this MsgVpn&#39;s jndiConnectionFactories collection. Available since 2.2. */
    public var jndiConnectionFactoriesUri: String?
    /** The URI of this MsgVpn&#39;s jndiQueues collection. Available since 2.2. */
    public var jndiQueuesUri: String?
    /** The URI of this MsgVpn&#39;s jndiTopics collection. Available since 2.2. */
    public var jndiTopicsUri: String?
    /** The URI of this MsgVpn&#39;s mqttSessions collection. Available since 2.1. */
    public var mqttSessionsUri: String?
    /** The URI of this MsgVpn&#39;s queues collection. */
    public var queuesUri: String?
    /** The URI of this MsgVpn&#39;s replayLogs collection. Available since 2.10. */
    public var replayLogsUri: String?
    /** The URI of this MsgVpn&#39;s replicatedTopics collection. Available since 2.9. */
    public var replicatedTopicsUri: String?
    /** The URI of this MsgVpn&#39;s restDeliveryPoints collection. */
    public var restDeliveryPointsUri: String?
    /** The URI of this MsgVpn&#39;s sequencedTopics collection. */
    public var sequencedTopicsUri: String?
    /** The URI of this MsgVpn&#39;s topicEndpoints collection. Available since 2.1. */
    public var topicEndpointsUri: String?
    /** The URI of this MsgVpn object. */
    public var uri: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["aclProfilesUri"] = self.aclProfilesUri
        nillableDictionary["authorizationGroupsUri"] = self.authorizationGroupsUri
        nillableDictionary["bridgesUri"] = self.bridgesUri
        nillableDictionary["clientProfilesUri"] = self.clientProfilesUri
        nillableDictionary["clientUsernamesUri"] = self.clientUsernamesUri
        nillableDictionary["jndiConnectionFactoriesUri"] = self.jndiConnectionFactoriesUri
        nillableDictionary["jndiQueuesUri"] = self.jndiQueuesUri
        nillableDictionary["jndiTopicsUri"] = self.jndiTopicsUri
        nillableDictionary["mqttSessionsUri"] = self.mqttSessionsUri
        nillableDictionary["queuesUri"] = self.queuesUri
        nillableDictionary["replayLogsUri"] = self.replayLogsUri
        nillableDictionary["replicatedTopicsUri"] = self.replicatedTopicsUri
        nillableDictionary["restDeliveryPointsUri"] = self.restDeliveryPointsUri
        nillableDictionary["sequencedTopicsUri"] = self.sequencedTopicsUri
        nillableDictionary["topicEndpointsUri"] = self.topicEndpointsUri
        nillableDictionary["uri"] = self.uri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
