//
// MsgVpnRestDeliveryPointLinks.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class MsgVpnRestDeliveryPointLinks: JSONEncodable {
    /** The URI of this MsgVpnRestDeliveryPoint&#39;s queueBindings collection. */
    public var queueBindingsUri: String?
    /** The URI of this MsgVpnRestDeliveryPoint&#39;s restConsumers collection. */
    public var restConsumersUri: String?
    /** The URI of this MsgVpnRestDeliveryPoint object. */
    public var uri: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["queueBindingsUri"] = self.queueBindingsUri
        nillableDictionary["restConsumersUri"] = self.restConsumersUri
        nillableDictionary["uri"] = self.uri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
