//
// MsgVpnBridgeLinks.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class MsgVpnBridgeLinks: JSONEncodable {
    /** The URI of this MsgVpnBridge&#39;s remoteMsgVpns collection. */
    public var remoteMsgVpnsUri: String?
    /** The URI of this MsgVpnBridge&#39;s remoteSubscriptions collection. */
    public var remoteSubscriptionsUri: String?
    /** The URI of this MsgVpnBridge&#39;s tlsTrustedCommonNames collection. */
    public var tlsTrustedCommonNamesUri: String?
    /** The URI of this MsgVpnBridge object. */
    public var uri: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["remoteMsgVpnsUri"] = self.remoteMsgVpnsUri
        nillableDictionary["remoteSubscriptionsUri"] = self.remoteSubscriptionsUri
        nillableDictionary["tlsTrustedCommonNamesUri"] = self.tlsTrustedCommonNamesUri
        nillableDictionary["uri"] = self.uri
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
