//
// MsgVpnAclProfilePublishException.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class MsgVpnAclProfilePublishException: JSONEncodable {
    public enum TopicSyntax: String { 
        case Smf = "smf"
        case Mqtt = "mqtt"
    }
    /** The name of the ACL Profile. */
    public var aclProfileName: String?
    /** The name of the Message VPN. */
    public var msgVpnName: String?
    /** The name of the Topic for the Exception to the default action taken. May include wildcard characters. */
    public var publishExceptionTopic: String?
    /** The syntax of the Topic for the Exception to the default action taken. The allowed values and their meaning are:  &lt;pre&gt; \&quot;smf\&quot; - Topic uses SMF syntax. \&quot;mqtt\&quot; - Topic uses MQTT syntax. &lt;/pre&gt;  */
    public var topicSyntax: TopicSyntax?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["aclProfileName"] = self.aclProfileName
        nillableDictionary["msgVpnName"] = self.msgVpnName
        nillableDictionary["publishExceptionTopic"] = self.publishExceptionTopic
        nillableDictionary["topicSyntax"] = self.topicSyntax?.rawValue
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
