//
// MsgVpnMqttSession.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class MsgVpnMqttSession: JSONEncodable {
    public enum MqttSessionVirtualRouter: String { 
        case Primary = "primary"
        case Backup = "backup"
    }
    /** Enable or disable the MQTT Session. When disabled, the client is disconnected, new messages matching QoS 0 subscriptions are discarded, and new messages matching QoS 1 subscriptions are stored for future delivery. The default value is &#x60;false&#x60;. */
    public var enabled: Bool?
    /** The Client ID of the MQTT Session, which corresponds to the ClientId provided in the MQTT CONNECT packet. */
    public var mqttSessionClientId: String?
    /** The Virtual Router of the MQTT Session. The allowed values and their meaning are:  &lt;pre&gt; \&quot;primary\&quot; - The MQTT Session belongs to the primary Virtual Router. \&quot;backup\&quot; - The MQTT Session belongs to the backup Virtual Router. &lt;/pre&gt;  */
    public var mqttSessionVirtualRouter: MqttSessionVirtualRouter?
    /** The name of the Message VPN. */
    public var msgVpnName: String?
    /** The owner of the MQTT Session. For externally-created sessions this defaults to the Client Username of the connecting client. For management-created sessions this defaults to empty. Before configuring, the MQTT Session must be disabled. The default value is &#x60;\&quot;\&quot;&#x60;. */
    public var owner: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["enabled"] = self.enabled
        nillableDictionary["mqttSessionClientId"] = self.mqttSessionClientId
        nillableDictionary["mqttSessionVirtualRouter"] = self.mqttSessionVirtualRouter?.rawValue
        nillableDictionary["msgVpnName"] = self.msgVpnName
        nillableDictionary["owner"] = self.owner
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
