//
// MsgVpnAuthorizationGroup.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class MsgVpnAuthorizationGroup: JSONEncodable {
    /** The ACL Profile of the LDAP Authorization Group. The default value is &#x60;\&quot;default\&quot;&#x60;. */
    public var aclProfileName: String?
    /** The name of the LDAP Authorization Group. */
    public var authorizationGroupName: String?
    /** The Client Profile of the LDAP Authorization Group. The default value is &#x60;\&quot;default\&quot;&#x60;. */
    public var clientProfileName: String?
    /** Enable or disable the LDAP Authorization Group in the Message VPN. The default value is &#x60;false&#x60;. */
    public var enabled: Bool?
    /** The name of the Message VPN. */
    public var msgVpnName: String?
    /** Lower the priority to be less than this group. The default is not applicable. The default is not applicable. */
    public var orderAfterAuthorizationGroupName: String?
    /** Raise the priority to be greater than this group. The default is not applicable. The default is not applicable. */
    public var orderBeforeAuthorizationGroupName: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["aclProfileName"] = self.aclProfileName
        nillableDictionary["authorizationGroupName"] = self.authorizationGroupName
        nillableDictionary["clientProfileName"] = self.clientProfileName
        nillableDictionary["enabled"] = self.enabled
        nillableDictionary["msgVpnName"] = self.msgVpnName
        nillableDictionary["orderAfterAuthorizationGroupName"] = self.orderAfterAuthorizationGroupName
        nillableDictionary["orderBeforeAuthorizationGroupName"] = self.orderBeforeAuthorizationGroupName
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
