//
// MsgVpnAclProfileClientConnectException.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class MsgVpnAclProfileClientConnectException: JSONEncodable {
    /** The name of the ACL Profile. */
    public var aclProfileName: String?
    /** The IP Address/Netmask of the Client Connect Exception in the Classless Inter-Domain Routing (CIDR) form. */
    public var clientConnectExceptionAddress: String?
    /** The name of the Message VPN. */
    public var msgVpnName: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["aclProfileName"] = self.aclProfileName
        nillableDictionary["clientConnectExceptionAddress"] = self.clientConnectExceptionAddress
        nillableDictionary["msgVpnName"] = self.msgVpnName
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
