//
// MsgVpnClientUsername.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class MsgVpnClientUsername: JSONEncodable {
    /** The ACL Profile of the Client Username. The default value is &#x60;\&quot;default\&quot;&#x60;. */
    public var aclProfileName: String?
    /** The Client Profile of the Client Username. The default value is &#x60;\&quot;default\&quot;&#x60;. */
    public var clientProfileName: String?
    /** The value of the Client Username. */
    public var clientUsername: String?
    /** Enables or disables the Client Username. When disabled all clients currently connected as the Client Username are disconnected. The default value is &#x60;false&#x60;. */
    public var enabled: Bool?
    /** Enables or disables guaranteed endpoint permission override for the Client Username. When enabled all guaranteed endpoints may be accessed, modified or deleted with the same permission as the owner. The default value is &#x60;false&#x60;. */
    public var guaranteedEndpointPermissionOverrideEnabled: Bool?
    /** The name of the Message VPN. */
    public var msgVpnName: String?
    /** The password of this Client Username for internal Authentication. The default is to have no password. The default is to have no &#x60;password&#x60;. */
    public var password: String?
    /** Enables or disables the subscription management capability of the Client Username. This is the ability to manage subscriptions on behalf of other Client Usernames. The default value is &#x60;false&#x60;. */
    public var subscriptionManagerEnabled: Bool?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["aclProfileName"] = self.aclProfileName
        nillableDictionary["clientProfileName"] = self.clientProfileName
        nillableDictionary["clientUsername"] = self.clientUsername
        nillableDictionary["enabled"] = self.enabled
        nillableDictionary["guaranteedEndpointPermissionOverrideEnabled"] = self.guaranteedEndpointPermissionOverrideEnabled
        nillableDictionary["msgVpnName"] = self.msgVpnName
        nillableDictionary["password"] = self.password
        nillableDictionary["subscriptionManagerEnabled"] = self.subscriptionManagerEnabled
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
