//
// SempError.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class SempError: JSONEncodable {
    /** The error code which uniquely identifies the error that has occurred. */
    public var code: Int32?
    /** The verbose description of the problem. */
    public var description: String?
    /** The terse status string associated with &#x60;code&#x60;. */
    public var status: String?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["code"] = self.code?.encodeToJSON()
        nillableDictionary["description"] = self.description
        nillableDictionary["status"] = self.status
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
