//
// SempMeta.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class SempMeta: JSONEncodable {
    public var error: SempError?
    public var paging: SempPaging?
    public var request: SempRequest?
    /** The HTTP response code, one of 200 (success), 4xx (client error), or 5xx (server error). */
    public var responseCode: Int32?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["error"] = self.error?.encodeToJSON()
        nillableDictionary["paging"] = self.paging?.encodeToJSON()
        nillableDictionary["request"] = self.request?.encodeToJSON()
        nillableDictionary["responseCode"] = self.responseCode?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
